### PR TITLE
Minor fixes you may consider

### PR DESCRIPTION
**Pull request by lemire**
This gets me closer to a clean build, but a problem with googletest remains.

(Feel free to ignore this PR.)

### CODE REVIEW

**Comment by veluca93** [comment]
Thank you for the pull request!
Interestingly, cmake works without issues for me - I suppose I have a newer version.
I guess that the changes to the C++ code are for OSX?

As for gtest - you could try running `make encoder decoder` instead of `make`, which should not require gtest as a dependency.
Otherwise, what is the problem you are encountering with gtest?

**Comment by lemire** [comment]
> I suppose I have a newer version.

I am on 3.19.1:

Screen Shot 2021-01-20 at 9 38 49 AM

**Comment by veluca93** [comment]
> > I suppose I have a newer version.
> 
> I am on 3.19.1:
> 
> Screen Shot 2021-01-20 at 9 38 49 AM

I am on 3.19.3 - it shouldn't be so different... Anyway, I'll merge this.

**Comment by lemire** [comment]
> As for gtest - you could try running make encoder decoder instead of make, which should not require gtest as a dependency. As for gtest - you could try running make encoder decoder instead of make, which should not require gtest as a dependency. Otherwise, what is the problem you are encountering with gtest?

With the changes in this PR, `cmake --build build --target encoder decoder` completes without error.

Otherwise, I get...

Screen Shot 2021-01-20 at 9 41 32 AM

My repository does not contain `gtest.h`.

**Comment by lemire** [comment]
> I guess that the changes to the C++ code are for OSX?

FreeBSD.

**Comment by lemire** [comment]
... oh and yes, it will work under macOS with these changes...

**Comment by veluca93** [comment]
gtest should be installed on the system - on Debian it would be
`sudo apt install libgtest-dev`
but I don't know what would be the corresponding command for FreeBSD or macOS.

**Comment by lemire** [comment]
I see it now...

> Note that to compile and run tests `googletest` should be installed on your system.

So all is good from my end.

**Pull request merged**
